# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo 'value=[\"a\", \"b\", \"c\"]' >> $GITHUB_OUTPUT
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
       matrix:
         value: ${{fromJson('["a", "b"]')}}
         #value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
         echo "${{ matrix.value }}"
#          echo "matrix -- ${{ needs.setup.outputs.matrix }}"
