# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - id: matrix
        run: |
          python getdirs.py >> $GITHUB_OUTPUT

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
       matrix:
         value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Build ${{ matrix.value }}
        run: ls
