# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - id: matrix
        run: |
          python getdirs.py >> $GITHUB_OUTPUT

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
       matrix:
         value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::903413632582:role/github_oidc_lambda
          aws-region: us-east-1
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: Build ${{ matrix.value }}
        run: FN_DIR=${{ matrix.value }} npm run build
      - name: Update ${{ matrix.value}} lambda function
        run: aws lambda update-function-code --function-name ${{ matrix.value }} --zip-file fileb://functions/${{ matrix.value }}/dist/index.zip